# Generated by Django 3.0.1 on 2019-12-24 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('summary', models.TextField(blank=True)),
                ('directorNm', models.CharField(blank=True, max_length=45)),
                ('prdtYear', models.IntegerField(blank=True, null=True)),
                ('openDt', models.IntegerField(blank=True, null=True)),
                ('showTm', models.IntegerField(blank=True, null=True)),
                ('nationNm', models.CharField(blank=True, max_length=45, null=True)),
                ('actorsNm', models.CharField(blank=True, max_length=150, null=True)),
                ('watchGradeNm', models.CharField(blank=True, max_length=100, null=True)),
                ('companyNmDict', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('userRating', models.CharField(blank=True, max_length=45, null=True)),
                ('audiAcc', models.CharField(blank=True, max_length=45, null=True)),
                ('thumbsNm', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbsImage', models.TextField(blank=True, null=True)),
                ('genresCds', models.ManyToManyField(blank=True, related_name='movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
